//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio.Algorithms.Assembly.Comparative.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bio.Algorithms.Assembly.Comparative.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4: Consensus Generation - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string ConsensusGenerationEnded {
            get {
                return ResourceManager.GetString("ConsensusGenerationEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4: Consensus Generation - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string ConsensusGenerationStarted {
            get {
                return ResourceManager.GetString("ConsensusGenerationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string DefaultSubStatus {
            get {
                return ResourceManager.GetString("DefaultSubStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Layout Refinement - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string LayoutRefinementEnded {
            get {
                return ResourceManager.GetString("LayoutRefinementEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Layout Refinement - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string LayoutRefinementStarted {
            get {
                return ResourceManager.GetString("LayoutRefinementStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parallelized comparative geonme assembler..
        /// </summary>
        internal static string PcaDescription {
            get {
                return ResourceManager.GetString("PcaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Comparative Genome Assembler.
        /// </summary>
        internal static string PcaName {
            get {
                return ResourceManager.GetString("PcaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Read Alignment - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string ReadAlignmentEnded {
            get {
                return ResourceManager.GetString("ReadAlignmentEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Read Alignment - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string ReadAlignmentStarted {
            get {
                return ResourceManager.GetString("ReadAlignmentStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Repeat Resolution - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string RepeatResolutionEnded {
            get {
                return ResourceManager.GetString("RepeatResolutionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Repeat Resolution - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string RepeatResolutionStarted {
            get {
                return ResourceManager.GetString("RepeatResolutionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5: Scaffold Generation - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string ScaffoldGenerationEnded {
            get {
                return ResourceManager.GetString("ScaffoldGenerationEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5: Scaffold Generation - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string ScaffoldGenerationStarted {
            get {
                return ResourceManager.GetString("ScaffoldGenerationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting Resolved Deltas - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string SortingResolvedDeltasEnded {
            get {
                return ResourceManager.GetString("SortingResolvedDeltasEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting Resolved Deltas - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string SortingResolvedDeltasStarted {
            get {
                return ResourceManager.GetString("SortingResolvedDeltasStarted", resourceCulture);
            }
        }
    }
}
