//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bio.Algorithms.Assembly.Padena.Properties.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one sequence should not contain Gap/Ambiguous character.
        /// </summary>
        internal static string AmbiguousCharacter {
            get {
                return ResourceManager.GetString("AmbiguousCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5: BuildContigs - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string BuildContigsEnded {
            get {
                return ResourceManager.GetString("BuildContigsEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5: BuildContigs - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string BuildContigsStarted {
            get {
                return ResourceManager.GetString("BuildContigsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 6: BuildScaffolds - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string BuildScaffoldEnded {
            get {
                return ResourceManager.GetString("BuildScaffoldEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 6: BuildScaffolds - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string BuildScaffoldStarted {
            get {
                return ResourceManager.GetString("BuildScaffoldStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Assemble RNA or Protein Sequences.
        /// </summary>
        internal static string CannotAssembleSequenceType {
            get {
                return ResourceManager.GetString("CannotAssembleSequenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 &amp; 2: Create Kmer and Graph - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string CreateGraphEnded {
            get {
                return ResourceManager.GetString("CreateGraphEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 &amp; 2: Create Kmer and Graph - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string CreateGraphStarted {
            get {
                return ResourceManager.GetString("CreateGraphStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sequence(s) skipped outof {1} processed sequences..
        /// </summary>
        internal static string CreateGraphSubStatus {
            get {
                return ResourceManager.GetString("CreateGraphSubStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sequence(s) processed..
        /// </summary>
        internal static string CreateGraphSubStatusWithoutSkipped {
            get {
                return ResourceManager.GetString("CreateGraphSubStatusWithoutSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DanglingLinksPurger.
        /// </summary>
        internal static string DanglingLinksPurger {
            get {
                return ResourceManager.GetString("DanglingLinksPurger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error correction module by removal of dangling links in graph.
        /// </summary>
        internal static string DanglingLinksPurgerDescription {
            get {
                return ResourceManager.GetString("DanglingLinksPurgerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string DefaultSubStatus {
            get {
                return ResourceManager.GetString("DefaultSubStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth cannot be less than or equal to 0.
        /// </summary>
        internal static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate read found. Id:{0}.
        /// </summary>
        internal static string DuplicatingReadIds {
            get {
                return ResourceManager.GetString("DuplicatingReadIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Estimating default values - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string EstimateDefaultValuesEnded {
            get {
                return ResourceManager.GetString("EstimateDefaultValuesEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Estimating default values - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string EstimateDefaultValuesStarted {
            get {
                return ResourceManager.GetString("EstimateDefaultValuesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Generate Links Ended..
        /// </summary>
        internal static string GenerateLinkEnded {
            get {
                return ResourceManager.GetString("GenerateLinkEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Generate Links Started..
        /// </summary>
        internal static string GenerateLinkStarted {
            get {
                return ResourceManager.GetString("GenerateLinkStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Graph built successfully - Processed {0} sequences..
        /// </summary>
        internal static string GraphBuilt {
            get {
                return ResourceManager.GetString("GraphBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes in graph: {0}.
        /// </summary>
        internal static string GraphNodeCountDisplay {
            get {
                return ResourceManager.GetString("GraphNodeCountDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kmer length must be less than the length of the shortest sequence, and should be greater than half the length of the longest sequence..
        /// </summary>
        internal static string InappropriateKmerLength {
            get {
                return ResourceManager.GetString("InappropriateKmerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string InitializingEnded {
            get {
                return ResourceManager.GetString("InitializingEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string InitializingStarted {
            get {
                return ResourceManager.GetString("InitializingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the sequences in list is null. All sequences in input list must be valid sequences..
        /// </summary>
        internal static string InputSequenceCannotBeNull {
            get {
                return ResourceManager.GetString("InputSequenceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kmer length cannot be less than or equal to 0.
        /// </summary>
        internal static string KmerLength {
            get {
                return ResourceManager.GetString("KmerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundancy value cannot be negative.
        /// </summary>
        internal static string NegativeRedundancy {
            get {
                return ResourceManager.GetString("NegativeRedundancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contig Builder cannot be null.
        /// </summary>
        internal static string NullContigBuilder {
            get {
                return ResourceManager.GetString("NullContigBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padena.
        /// </summary>
        internal static string Padena {
            get {
                return ResourceManager.GetString("Padena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implements parallel de-novo assembly using De-bruijn graph.
        /// </summary>
        internal static string PadenaDescription {
            get {
                return ResourceManager.GetString("PadenaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Paired Read Data.
        /// </summary>
        internal static string PairedReadException {
            get {
                return ResourceManager.GetString("PairedReadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedundantPathsPurger.
        /// </summary>
        internal static string RedundantPathsPurger {
            get {
                return ResourceManager.GetString("RedundantPathsPurger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph error correction by removal of redundant paths.
        /// </summary>
        internal static string RedundantPathsPurgerDescription {
            get {
                return ResourceManager.GetString("RedundantPathsPurgerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4: RemoveRedundancy - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string RemoveReducndancyEnded {
            get {
                return ResourceManager.GetString("RemoveReducndancyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4: RemoveRedundancy - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string RemoveReducndancyStarted {
            get {
                return ResourceManager.GetString("RemoveReducndancyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Secondary UndangleGraph - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string SecondaryUndangleGraphEnded {
            get {
                return ResourceManager.GetString("SecondaryUndangleGraphEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Secondary UndangleGraph - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string SecondaryUndangleGraphStarted {
            get {
                return ResourceManager.GetString("SecondaryUndangleGraphStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple path based contig builder.
        /// </summary>
        internal static string SimplePathContigBuilder {
            get {
                return ResourceManager.GetString("SimplePathContigBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds contigs from simple paths in the de bruijn graph.
        /// </summary>
        internal static string SimplePathContigBuilderDescription {
            get {
                return ResourceManager.GetString("SimplePathContigBuilderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time for Task: {0:c}.
        /// </summary>
        internal static string TimeSpanReport {
            get {
                return ResourceManager.GetString("TimeSpanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: UndangleGraph - End time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string UndangleGraphEnded {
            get {
                return ResourceManager.GetString("UndangleGraphEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: UndangleGraph - Start time: {0:yyyy-MM-dd-HH:mm:ss.fff}.
        /// </summary>
        internal static string UndangleGraphStarted {
            get {
                return ResourceManager.GetString("UndangleGraphStarted", resourceCulture);
            }
        }
    }
}
