//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio.WebServiceHandlers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bio.WebServiceHandlers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Blast hosted by Cloud Computing.
        /// </summary>
        internal static string AZURE_BLAST_DESCRIPTION {
            get {
                return ResourceManager.GetString("AZURE_BLAST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Blast service URI is invalid..
        /// </summary>
        internal static string AZURE_BLAST_INVALID_URI {
            get {
                return ResourceManager.GetString("AZURE_BLAST_INVALID_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure BLAST.
        /// </summary>
        internal static string AZURE_BLAST_NAME {
            get {
                return ResourceManager.GetString("AZURE_BLAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration is not set..
        /// </summary>
        internal static string AZURE_BLAST_NULL_CONFIGURATION {
            get {
                return ResourceManager.GetString("AZURE_BLAST_NULL_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLAST service hosted at BioHPC installation at CBSU (cbsuapps.tc.cornell.edu).
        /// </summary>
        internal static string BIOHPC_BLAST_DESCRIPTION {
            get {
                return ResourceManager.GetString("BIOHPC_BLAST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLAST @ BioHPC.
        /// </summary>
        internal static string BIOHPC_BLAST_NAME {
            get {
                return ResourceManager.GetString("BIOHPC_BLAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BioHPC job could not be created. Error: {0}.
        /// </summary>
        internal static string BIOHPCJOBNOTCREATED {
            get {
                return ResourceManager.GetString("BIOHPCJOBNOTCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BioHPC job {0} could not be submitted. Error: {1}.
        /// </summary>
        internal static string BIOHPCJOBNOTSUBMITTED {
            get {
                return ResourceManager.GetString("BIOHPCJOBNOTSUBMITTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the requested BioHPC databases are not DNA or are not available.
        /// </summary>
        internal static string BIOHPCNODNADB {
            get {
                return ResourceManager.GetString("BIOHPCNODNADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the requested databases are not protein or are not available.
        /// </summary>
        internal static string BIOHPCNOPROTDB {
            get {
                return ResourceManager.GetString("BIOHPCNOPROTDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BioHPC Blast: no sequences to process.
        /// </summary>
        internal static string BIOHPCNOSEQUENCE {
            get {
                return ResourceManager.GetString("BIOHPCNOSEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BioHPC Blast: no sequences to process.
        /// </summary>
        internal static string BIOHPCREQIDBAD {
            get {
                return ResourceManager.GetString("BIOHPCREQIDBAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BioHPC Blast: requestIdentifier null or empty.
        /// </summary>
        internal static string BIOHPCREQIDEMPTY {
            get {
                return ResourceManager.GetString("BIOHPCREQIDEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BioHPC server could not be contacted to create a job..
        /// </summary>
        internal static string BIOHPCSERVERABSENT {
            get {
                return ResourceManager.GetString("BIOHPCSERVERABSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed on request &apos;{0}&apos; (status {1}, &apos;{2}&apos;)..
        /// </summary>
        internal static string BLASTREQUESTFAILED {
            get {
                return ResourceManager.GetString("BLASTREQUESTFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of retries exceeded, giving up on request &apos;{0}&apos; (status {1}, &apos;{2}&apos;)..
        /// </summary>
        internal static string BLASTRETRIESEXCEEDED {
            get {
                return ResourceManager.GetString("BLASTRETRIESEXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.ncbi.nlm.nih.gov/blast/Blast.cgi.
        /// </summary>
        internal static string DEFAULTNCBIBLASTSERVICEURI {
            get {
                return ResourceManager.GetString("DEFAULTNCBIBLASTSERVICEURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WU-BLAST Web Service hosted by EBI (www.ebi.ac.uk).
        /// </summary>
        internal static string EBIWUBLAST_DESCRIPTION {
            get {
                return ResourceManager.GetString("EBIWUBLAST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBI WU-BLAST.
        /// </summary>
        internal static string EBIWUBLAST_NAME {
            get {
                return ResourceManager.GetString("EBIWUBLAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get resultTypes..
        /// </summary>
        internal static string EBIWURESULTTYPEFAILED {
            get {
                return ResourceManager.GetString("EBIWURESULTTYPEFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service response was empty. Request: {0}..
        /// </summary>
        internal static string EMPTYRESPONSE {
            get {
                return ResourceManager.GetString("EMPTYRESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitHttpRequest failed. Status: {0}..
        /// </summary>
        internal static string HTTPSUBMITFAILED {
            get {
                return ResourceManager.GetString("HTTPSUBMITFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filter setting: &apos;{0}&apos;. Valid values are : {1}.
        /// </summary>
        internal static string INVALIDBLASTFILTER {
            get {
                return ResourceManager.GetString("INVALIDBLASTFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GeneticCode value is not allowed. Valid values: 1..16, 21, or 22..
        /// </summary>
        internal static string INVALIDGENETICCODE {
            get {
                return ResourceManager.GetString("INVALIDGENETICCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got HTML status, expected XML. Status: {0}..
        /// </summary>
        internal static string INVALIDNCBISTATUS {
            get {
                return ResourceManager.GetString("INVALIDNCBISTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The QBLAST Web Service hosted by NCBI (www.ncbi.nlm.nih.gov).
        /// </summary>
        internal static string NCBIQBLAST_DESCRIPTION {
            get {
                return ResourceManager.GetString("NCBIQBLAST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCBI QBLAST.
        /// </summary>
        internal static string NCBIQBLAST_NAME {
            get {
                return ResourceManager.GetString("NCBIQBLAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBF Client.
        /// </summary>
        internal static string OWNERVALUE {
            get {
                return ResourceManager.GetString("OWNERVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Database parameter is required..
        /// </summary>
        internal static string PARAMETERDATABASEREQUIRED {
            get {
                return ResourceManager.GetString("PARAMETERDATABASEREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email parameter is required..
        /// </summary>
        internal static string PARAMETEREMAILREQUIRED {
            get {
                return ResourceManager.GetString("PARAMETEREMAILREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FormatType parameter cannot be set by the user..
        /// </summary>
        internal static string PARAMETERFORMATTYPENOTALLOWED {
            get {
                return ResourceManager.GetString("PARAMETERFORMATTYPENOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Program parameter is required..
        /// </summary>
        internal static string PARAMETERPROGRAMREQUIRED {
            get {
                return ResourceManager.GetString("PARAMETERPROGRAMREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QueryTo value.
        /// </summary>
        internal static string PARAMETERQUERYTOINVALID {
            get {
                return ResourceManager.GetString("PARAMETERQUERYTOINVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Query parameter (or a sequence argument) is required..
        /// </summary>
        internal static string PARAMETERSEQUENCEEMPTY {
            get {
                return ResourceManager.GetString("PARAMETERSEQUENCEEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Query parameter (or a sequence argument) is required..
        /// </summary>
        internal static string PARAMETERSEQUENCEREQUIRED {
            get {
                return ResourceManager.GetString("PARAMETERSEQUENCEREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sequence Type parameter is required..
        /// </summary>
        internal static string PARAMETERSEQUENCETYPEREQUIRED {
            get {
                return ResourceManager.GetString("PARAMETERSEQUENCETYPEREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter \&quot;{0}\&quot; is not valid for Azure-BLAST..
        /// </summary>
        internal static string PARAMETERUNKNOWNAZURE {
            get {
                return ResourceManager.GetString("PARAMETERUNKNOWNAZURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter \&quot;{0}\&quot; is not valid for EBIWU BLAST..
        /// </summary>
        internal static string PARAMETERUNKNOWNEBIWU {
            get {
                return ResourceManager.GetString("PARAMETERUNKNOWNEBIWU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter \&quot;{0}\&quot; is not valid for NCBI QBLAST..
        /// </summary>
        internal static string PARAMETERUNKNOWNNCBI {
            get {
                return ResourceManager.GetString("PARAMETERUNKNOWNNCBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter \&quot;{0}\&quot; is not valid for BioHPC QBLAST..
        /// </summary>
        internal static string PARAMETRUNKNOWNBIOHPC {
            get {
                return ResourceManager.GetString("PARAMETRUNKNOWNBIOHPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract a requestIdentifier. Error: {0}..
        /// </summary>
        internal static string RIDEXTRACTFAILED {
            get {
                return ResourceManager.GetString("RIDEXTRACTFAILED", resourceCulture);
            }
        }
    }
}
