//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PadenaUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PadenaUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads containing ambiguous symbols are not supported..
        /// </summary>
        internal static string AmbiguousReadsNotSupported {
            get {
                return ResourceManager.GetString("AmbiguousReadsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:	 PadenaUtil.exe assemble [options] &lt;Read File&gt; 		
        ///Description: Assemble reads into contigs (No matepair information required.) 
        ///
        ///Optional Parameters:
        ///
        ///-h                 Help
        ///
        ///-q                 Display minimal output during processing.
        ///
        ///-k:&lt;int&gt;           Length of k-mer.
        ///
        ///-d:&lt;int&gt;           Threshold for removing 
        ///                   dangling ends in graph.
        ///
        ///-r:&lt;int&gt;    	   Length Threshold for 
        ///                   removing redundant paths in graph.
        ///-e:&lt;int&gt;           Threshold for er [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssembleHelp {
            get {
                return ResourceManager.GetString("AssembleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:	 PadenaUtil.exe assemblewithscaffold [options] &lt;Read File&gt; 		
        ///Description: Assemblewithscaffolds merges reads into scaffolds using matepair information.
        ///
        ///Optional Parameters:
        ///
        ///-h             Help
        ///
        ///-q             Display minimal output during processing.
        ///
        ///-n:&lt;string&gt;    Clone Library Name.
        ///
        ///-m:&lt;double&gt;    Mean Length of clone library. 
        ///
        ///-s:&lt;double&gt;    Standard Deviation of Clone Library.
        ///
        ///-b:&lt;int&gt;       Number of paired read required to 
        ///	       connect two contigs.
        ///
        ///-f:&lt;int&gt;       D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssembleWithScaffoldHelp {
            get {
                return ResourceManager.GetString("AssembleWithScaffoldHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning assembly and scaffold processing..
        /// </summary>
        internal static string AssemblyScaffoldStarting {
            get {
                return ResourceManager.GetString("AssemblyScaffoldStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning assembly processing..
        /// </summary>
        internal static string AssemblyStarting {
            get {
                return ResourceManager.GetString("AssemblyStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: kmerLength is set to an even value ({0}) which can lead to infinite loops when building the graphs.
        ///It is recommended that you use odd numbers to ensure palindrome sequences do not lead to infinite recursion.
        ///    .
        /// </summary>
        internal static string BadKmerLength {
            get {
                return ResourceManager.GetString("BadKmerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue (Y/N)?.
        /// </summary>
        internal static string ContinuePrompt {
            get {
                return ResourceManager.GetString("ContinuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padena Utility v2.0
        ///Copyright (c) 2011-2014, The Outercurve Foundation.
        ///.
        /// </summary>
        internal static string PadenaSplashScreen {
            get {
                return ResourceManager.GetString("PadenaSplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:	   PadenaUtil.exe command [options]
        ///Description: Assembles reads into Contigs or scaffold 
        ///using mate pair information.
        ///
        ///Command:   
        ///
        ///Assemble:              Assemble reads into contigs 
        ///		       (No matepair information required.) 
        ///
        ///Scaffold:     	       Scaffold uses mate pair information 
        ///		       to merge contigs into scaffolds.
        ///
        ///AssembleWithScaffold:  Assemble reads into scaffolds using 
        ///                       matepair information..
        /// </summary>
        internal static string PadenaUtilHelp {
            get {
                return ResourceManager.GetString("PadenaUtilHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak memory in the virtual memory paging file used: {0}.
        /// </summary>
        internal static string PeakPagedMemorySize64 {
            get {
                return ResourceManager.GetString("PeakPagedMemorySize64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak virtual memory used: {0}.
        /// </summary>
        internal static string PeakVirtualMemorySize64 {
            get {
                return ResourceManager.GetString("PeakVirtualMemorySize64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak physical memory used: {0}.
        /// </summary>
        internal static string PeakWorkingSet64 {
            get {
                return ResourceManager.GetString("PeakWorkingSet64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference File not in correct format.
        /// </summary>
        internal static string ReferenceFile {
            get {
                return ResourceManager.GetString("ReferenceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:	 PADENAUtil.exe scaffold [options] &lt;Contig file&gt; &lt;Read File&gt; 		
        ///Description: Scaffold uses mate pair information to merge contigs into scaffolds.
        ///
        ///Required Parameters:
        ///
        ///-k:&lt;int&gt;           Length of k-mer.
        ///
        ///Optional Parameters:
        ///
        ///-h                 Help.
        ///
        ///-q                 Display minimal output during processing.
        ///
        ///-o:&lt;string&gt;        Output file.
        ///
        ///-n:&lt;string&gt;        Clone Library Name.
        ///
        ///-m:&lt;double&gt;        Mean Length of clone library.
        ///
        ///-s:&lt;double&gt;  	   Standard Deviation of Clone Li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScaffoldHelp {
            get {
                return ResourceManager.GetString("ScaffoldHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning scaffold processing..
        /// </summary>
        internal static string ScaffoldStarting {
            get {
                return ResourceManager.GetString("ScaffoldStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total CPU time taken: {0}.
        /// </summary>
        internal static string TotalProcessorTime {
            get {
                return ResourceManager.GetString("TotalProcessorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {0}
        ///.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
    }
}
