//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeveloperPreRequisiteCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeveloperPreRequisiteCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure new path (y/n) :.
        /// </summary>
        internal static string ACCEPT_CHOICE {
            get {
                return ResourceManager.GetString("ACCEPT_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new path (e.g., {0}) :.
        /// </summary>
        internal static string ACCEPT_FILEPATH {
            get {
                return ResourceManager.GetString("ACCEPT_FILEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel 2007.
        /// </summary>
        internal static string EXCEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Microsoft Office (Excel) version {0}..
        /// </summary>
        internal static string EXCEL_FOUND {
            get {
                return ResourceManager.GetString("EXCEL_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        internal static string EXCEL_NAME {
            get {
                return ResourceManager.GetString("EXCEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office (Excel) version check failed. .NET Bio may not compile or run as expected because a required version of component was not found. Please install Microsoft Office (Excel) 2007 or above..
        /// </summary>
        internal static string EXCEL_NOTFOUND {
            get {
                return ResourceManager.GetString("EXCEL_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html Help Compiler.
        /// </summary>
        internal static string HHC_DESCRIPTION {
            get {
                return ResourceManager.GetString("HHC_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Html Help Compiler version {0}..
        /// </summary>
        internal static string HHC_FOUND {
            get {
                return ResourceManager.GetString("HHC_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HHC.
        /// </summary>
        internal static string HHC_NAME {
            get {
                return ResourceManager.GetString("HHC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html Help Compiler version check failed. .NET Bio may not compile or run as expected because a required version of component was not found. Please install Html Help Compiler {0} or above from http://www.microsoft.com/downloads/details.aspx?FamilyID=00535334-c8a6-452f-9aa0-d597d16580cc&amp;DisplayLang=en..
        /// </summary>
        internal static string HHC_NOTFOUND {
            get {
                return ResourceManager.GetString("HHC_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key ....
        /// </summary>
        internal static string PRESS_KEY {
            get {
                return ResourceManager.GetString("PRESS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry not found. {0}\{1}..
        /// </summary>
        internal static string REGISTRY_NOT_FOUND {
            get {
                return ResourceManager.GetString("REGISTRY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SandCastle..
        /// </summary>
        internal static string SANDCASTLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("SANDCASTLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found SandCastle version {0}. .
        /// </summary>
        internal static string SANDCASTLE_FOUND {
            get {
                return ResourceManager.GetString("SANDCASTLE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SandCastle.
        /// </summary>
        internal static string SANDCASTLE_NAME {
            get {
                return ResourceManager.GetString("SANDCASTLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SandCastle version check failed. .NET Bio may not compile or run as expected because a required version of component was not found. Please install SandCastle {0} or above from http://sandcastle.codeplex.com/.
        /// </summary>
        internal static string SANDCASTLE_NOTFOUND {
            get {
                return ResourceManager.GetString("SANDCASTLE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch &quot;{0}&quot; Unknown..
        /// </summary>
        internal static string UNKNOWN_SWITCH {
            get {
                return ResourceManager.GetString("UNKNOWN_SWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown swithces in command line..
        /// </summary>
        internal static string UNKNOWN_SWITCHES {
            get {
                return ResourceManager.GetString("UNKNOWN_SWITCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio Office Runtime..
        /// </summary>
        internal static string VSTO_DESCRIPTION {
            get {
                return ResourceManager.GetString("VSTO_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Visual Studio Tool for Office Runtime version {0}..
        /// </summary>
        internal static string VSTO_FOUND {
            get {
                return ResourceManager.GetString("VSTO_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTO.
        /// </summary>
        internal static string VSTO_NAME {
            get {
                return ResourceManager.GetString("VSTO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools for Office Runtime version check failed. .NET Bio may not compile or run as expected because a required version of component was not found. Please install Visual Studio Tool for Office Runtime 4 or above from http://www.microsoft.com/downloads/en/details.aspx?familyid=f4d7a5a1-8ca8-489d-97eb-663a54d609a0&amp;displaylang=en.
        /// </summary>
        internal static string VSTO_NOTFOUND {
            get {
                return ResourceManager.GetString("VSTO_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer Xml..
        /// </summary>
        internal static string WIX_DESCRIPTION {
            get {
                return ResourceManager.GetString("WIX_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found WiX version {0}. 
        ///Ensure that file “MBI\BuildTools\ToolSource\ExternalTools\wix3\{1}” is copied to &quot;{2}&quot;...
        /// </summary>
        internal static string WIX_FOUND {
            get {
                return ResourceManager.GetString("WIX_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIX.
        /// </summary>
        internal static string WIX_NAME {
            get {
                return ResourceManager.GetString("WIX_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiX version check failed. .NET Bio may not compile or run as expected because a required version of component was not found. Please install WiX {0} or above from http://wix.codeplex.com/releases/view/44406..
        /// </summary>
        internal static string WIX_NOTFOUND {
            get {
                return ResourceManager.GetString("WIX_NOTFOUND", resourceCulture);
            }
        }
    }
}
