//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleClusterApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleClusterApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: SampleClusterApp is an example command-line utility that take a 
        ///list of sequences from an input FastA file and performs GC Content operation. 
        ///The results are stored in a result file named Results.txt by default. This can 
        ///also be used to distribute the work across an HPC cluster, or as a parameter 
        ///to the DistributeApp.exe distribution example.
        ///
        ///Usage: SampleClusterApp.exe test.fa [/ResultFile results.txt] [options]
        ///
        ////help                Show the help information with program options  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleClusterApp_Help {
            get {
                return ResourceManager.GetString("SampleClusterApp_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleClusterApp v2.0 - Sample distributable application to calculate GC content of given Sequence
        ///Copyright (c) 2011-2014, The Outercurve Foundation.
        ///.
        /// </summary>
        internal static string SampleClusterApp_Splash {
            get {
                return ResourceManager.GetString("SampleClusterApp_Splash", resourceCulture);
            }
        }
    }
}
