//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.VennDiagram.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tools.VennDiagram.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VennDiagramData already scaled..
        /// </summary>
        internal static string AlreadyScaled {
            get {
                return ResourceManager.GetString("AlreadyScaled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;Auto Layout on Open&apos; row in the per-workbook settings table. Is this NodeXL version 1.0.1.108 or later?.
        /// </summary>
        internal static string AutolayoutOnOpenMissing {
            get {
                return ResourceManager.GetString("AutolayoutOnOpenMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of Basepairs.
        /// </summary>
        internal static string BasePairsCountLabel {
            get {
                return ResourceManager.GetString("BasePairsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create venn diagram with the given input : Given regions are not overlapping properly..
        /// </summary>
        internal static string InvalidOverlappingError {
            get {
                return ResourceManager.GetString("InvalidOverlappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing one or more expected columns in the NodeXL worksheet..
        /// </summary>
        internal static string NodeXLColumnMissing {
            get {
                return ResourceManager.GetString("NodeXLColumnMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeXL is not installed..
        /// </summary>
        internal static string NodeXLNotInstalled {
            get {
                return ResourceManager.GetString("NodeXLNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feasible solution..
        /// </summary>
        internal static string NoFeasibleSolution {
            get {
                return ResourceManager.GetString("NoFeasibleSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VennDiagram requires 3 or 7 non-zero regions..
        /// </summary>
        internal static string NotEnoughRegions {
            get {
                return ResourceManager.GetString("NotEnoughRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only A.
        /// </summary>
        internal static string OnlyA {
            get {
                return ResourceManager.GetString("OnlyA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only AB.
        /// </summary>
        internal static string OnlyAB {
            get {
                return ResourceManager.GetString("OnlyAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only ABC.
        /// </summary>
        internal static string OnlyABC {
            get {
                return ResourceManager.GetString("OnlyABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only AC.
        /// </summary>
        internal static string OnlyAC {
            get {
                return ResourceManager.GetString("OnlyAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only B.
        /// </summary>
        internal static string OnlyB {
            get {
                return ResourceManager.GetString("OnlyB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only BC.
        /// </summary>
        internal static string OnlyBC {
            get {
                return ResourceManager.GetString("OnlyBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only C.
        /// </summary>
        internal static string OnlyC {
            get {
                return ResourceManager.GetString("OnlyC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string OverlapsSheetName {
            get {
                return ResourceManager.GetString("OverlapsSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Basepairs in Region.
        /// </summary>
        internal static string PerOfBasePairsInRegionLabel {
            get {
                return ResourceManager.GetString("PerOfBasePairsInRegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find per-workbook settings table..
        /// </summary>
        internal static string PerWorkbookTableMissing {
            get {
                return ResourceManager.GetString("PerWorkbookTableMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of Regions.
        /// </summary>
        internal static string RegionsCountLabel {
            get {
                return ResourceManager.GetString("RegionsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find vertex table..
        /// </summary>
        internal static string VertexTableMissing {
            get {
                return ResourceManager.GetString("VertexTableMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices.
        /// </summary>
        internal static string VerticesSheetName {
            get {
                return ResourceManager.GetString("VerticesSheetName", resourceCulture);
            }
        }
    }
}
