//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiodexExcel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiodexExcel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be parsed. The current operation will be terminated..
        /// </summary>
        internal static string ABORT_BED_PARSING {
            get {
                return ResourceManager.GetString("ABORT_BED_PARSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align sequences using  {0} algo.
        /// </summary>
        internal static string ALIGN_LABEL {
            get {
                return ResourceManager.GetString("ALIGN_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string ALIGNING {
            get {
                return ResourceManager.GetString("ALIGNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string ALIGNMENT {
            get {
                return ResourceManager.GetString("ALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligned Sequence.
        /// </summary>
        internal static string Alignment_AlignedSequencesHeading {
            get {
                return ResourceManager.GetString("Alignment_AlignedSequencesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment requires atleast 2 sequences. This workbook has less than 2 sequence. Please import another sequence and then align..
        /// </summary>
        internal static string ALIGNMENT_ATLEAST_2_SHEETS {
            get {
                return ResourceManager.GetString("ALIGNMENT_ATLEAST_2_SHEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Offset.
        /// </summary>
        internal static string Alignment_EndOffsetString {
            get {
                return ResourceManager.GetString("Alignment_EndOffsetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Offset.
        /// </summary>
        internal static string Alignment_StartOffsetString {
            get {
                return ResourceManager.GetString("Alignment_StartOffsetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment: {0}.
        /// </summary>
        internal static string ALIGNMENT_STATUS_BAR {
            get {
                return ResourceManager.GetString("ALIGNMENT_STATUS_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sheets.
        /// </summary>
        internal static string ALL_SHEETS {
            get {
                return ResourceManager.GetString("ALL_SHEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembling: {0}.
        /// </summary>
        internal static string ASSEMBLER_STATUS_BAR {
            get {
                return ResourceManager.GetString("ASSEMBLER_STATUS_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string ASSEMBLING {
            get {
                return ResourceManager.GetString("ASSEMBLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Pair Count.
        /// </summary>
        internal static string BASE_PAIR_COUNT {
            get {
                return ResourceManager.GetString("BASE_PAIR_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockCount.
        /// </summary>
        internal static string BED_BLOCK_COUNT {
            get {
                return ResourceManager.GetString("BED_BLOCK_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockSizes.
        /// </summary>
        internal static string BED_BLOCK_SIZES {
            get {
                return ResourceManager.GetString("BED_BLOCK_SIZES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockStarts.
        /// </summary>
        internal static string BED_BLOCK_STARTS {
            get {
                return ResourceManager.GetString("BED_BLOCK_STARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemRGB.
        /// </summary>
        internal static string BED_ITEM_RGB {
            get {
                return ResourceManager.GetString("BED_ITEM_RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BED_NAME {
            get {
                return ResourceManager.GetString("BED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string BED_SCORE {
            get {
                return ResourceManager.GetString("BED_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strand.
        /// </summary>
        internal static string BED_STRAND {
            get {
                return ResourceManager.GetString("BED_STRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThickEnd.
        /// </summary>
        internal static string BED_THICK_END {
            get {
                return ResourceManager.GetString("BED_THICK_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThickStart.
        /// </summary>
        internal static string BED_THICK_START {
            get {
                return ResourceManager.GetString("BED_THICK_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cancel the Blast request. {0}.
        /// </summary>
        internal static string BLAST_CANCEL_FAILED {
            get {
                return ResourceManager.GetString("BLAST_CANCEL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results were found.
        /// </summary>
        internal static string BLAST_NO_RESULT {
            get {
                return ResourceManager.GetString("BLAST_NO_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLAST_Results.
        /// </summary>
        internal static string BLAST_RESULTS {
            get {
                return ResourceManager.GetString("BLAST_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect alphabet type for the given sequence..
        /// </summary>
        internal static string CannotFindMatchingAlphabet {
            get {
                return ResourceManager.GetString("CannotFindMatchingAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Bio Extension for Excel.
        /// </summary>
        internal static string CAPTION {
            get {
                return ResourceManager.GetString("CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Charts {
            get {
                object obj = ResourceManager.GetObject("Charts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string CHROM_END {
            get {
                return ResourceManager.GetString("CHROM_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromosome.
        /// </summary>
        internal static string CHROM_ID {
            get {
                return ResourceManager.GetString("CHROM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string CHROM_START {
            get {
                return ResourceManager.GetString("CHROM_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseSelectionHelper {
            get {
                object obj = ResourceManager.GetObject("CloseSelectionHelper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clustered_Chart {
            get {
                object obj = ResourceManager.GetObject("Clustered_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string COMMON {
            get {
                return ResourceManager.GetString("COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sequence Item.
        /// </summary>
        internal static string CONTEXTMENU_DELETE {
            get {
                return ResourceManager.GetString("CONTEXTMENU_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Sequence Item.
        /// </summary>
        internal static string CONTEXTMENU_INSERT {
            get {
                return ResourceManager.GetString("CONTEXTMENU_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle color scheme.
        /// </summary>
        internal static string CONTEXTMENU_TOGGLE_COLORS {
            get {
                return ResourceManager.GetString("CONTEXTMENU_TOGGLE_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contig.
        /// </summary>
        internal static string CONTIG {
            get {
                return ResourceManager.GetString("CONTIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an entire sequence to BLAST..
        /// </summary>
        internal static string CONTIG_BLAST_ERROR {
            get {
                return ResourceManager.GetString("CONTIG_BLAST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msrerbio@microsoft.com.
        /// </summary>
        internal static string DEFAULT_EMAIL {
            get {
                return ResourceManager.GetString("DEFAULT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to em_rel.
        /// </summary>
        internal static string EM_REL {
            get {
                return ResourceManager.GetString("EM_REL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Query Region(s) found..
        /// </summary>
        internal static string EMPTY_SEQUENCE_RANGE {
            get {
                return ResourceManager.GetString("EMPTY_SEQUENCE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Value.
        /// </summary>
        internal static string EVALUE {
            get {
                return ResourceManager.GetString("EVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcelMetadata_CellLink.
        /// </summary>
        internal static string EXCEL_CELL_LINK {
            get {
                return ResourceManager.GetString("EXCEL_CELL_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Region.
        /// </summary>
        internal static string Export_BED_SequenceRangeString {
            get {
                return ResourceManager.GetString("Export_BED_SequenceRangeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save worksheet contents as {0} file .
        /// </summary>
        internal static string EXPORT_DESC {
            get {
                return ResourceManager.GetString("EXPORT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to {0}  files.
        /// </summary>
        internal static string EXPORT_LABEL {
            get {
                return ResourceManager.GetString("EXPORT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more quality value provided is invalid..
        /// </summary>
        internal static string ExportFasQ_InvalidQualityScore {
            get {
                return ResourceManager.GetString("ExportFasQ_InvalidQualityScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected sequence and its quality scores are not mapping properly..
        /// </summary>
        internal static string ExportFastQ_SequenceAndScoresNotMapping {
            get {
                return ResourceManager.GetString("ExportFastQ_SequenceAndScoresNotMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.Pattern.
        /// </summary>
        internal static string FPATTERN {
            get {
                return ResourceManager.GetString("FPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FromExcel {
            get {
                object obj = ResourceManager.GetObject("FromExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FromText {
            get {
                object obj = ResourceManager.GetObject("FromText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FromWeb {
            get {
                object obj = ResourceManager.GetObject("FromWeb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap openings.
        /// </summary>
        internal static string GAP_OPENINGS {
            get {
                return ResourceManager.GetString("GAP_OPENINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaps.
        /// </summary>
        internal static string GAPS {
            get {
                return ResourceManager.GetString("GAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURES.
        /// </summary>
        internal static string GenbankFeaturesHeader {
            get {
                return ResourceManager.GetString("GenbankFeaturesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accession.
        /// </summary>
        internal static string GenbankMetadataAccession {
            get {
                return ResourceManager.GetString("GenbankMetadataAccession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string GenbankMetadataAuthors {
            get {
                return ResourceManager.GetString("GenbankMetadataAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Count.
        /// </summary>
        internal static string GenbankMetadataBaseCount {
            get {
                return ResourceManager.GetString("GenbankMetadataBaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Levels.
        /// </summary>
        internal static string GenbankMetadataClassLevels {
            get {
                return ResourceManager.GetString("GenbankMetadataClassLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENT.
        /// </summary>
        internal static string GenbankMetadataComment {
            get {
                return ResourceManager.GetString("GenbankMetadataComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consortiums.
        /// </summary>
        internal static string GenbankMetadataConsortiums {
            get {
                return ResourceManager.GetString("GenbankMetadataConsortiums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string GenbankMetadataDate {
            get {
                return ResourceManager.GetString("GenbankMetadataDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBLink.
        /// </summary>
        internal static string GenbankMetadataDBLink {
            get {
                return ResourceManager.GetString("GenbankMetadataDBLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBSource.
        /// </summary>
        internal static string GenbankMetadataDBSource {
            get {
                return ResourceManager.GetString("GenbankMetadataDBSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        internal static string GenbankMetadataDefinition {
            get {
                return ResourceManager.GetString("GenbankMetadataDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Code.
        /// </summary>
        internal static string GenbankMetadataDivisionCode {
            get {
                return ResourceManager.GetString("GenbankMetadataDivisionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GI:.
        /// </summary>
        internal static string GenbankMetadataGI {
            get {
                return ResourceManager.GetString("GenbankMetadataGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METADATA.
        /// </summary>
        internal static string GenbankMetadataHeader {
            get {
                return ResourceManager.GetString("GenbankMetadataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string GenbankMetadataJournal {
            get {
                return ResourceManager.GetString("GenbankMetadataJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string GenbankMetadataKeywords {
            get {
                return ResourceManager.GetString("GenbankMetadataKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locus.
        /// </summary>
        internal static string GenbankMetadataLocus {
            get {
                return ResourceManager.GetString("GenbankMetadataLocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedLine.
        /// </summary>
        internal static string GenbankMetadataMedLine {
            get {
                return ResourceManager.GetString("GenbankMetadataMedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecule Type.
        /// </summary>
        internal static string GenbankMetadataMoleculeType {
            get {
                return ResourceManager.GetString("GenbankMetadataMoleculeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string GenbankMetadataName {
            get {
                return ResourceManager.GetString("GenbankMetadataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organism.
        /// </summary>
        internal static string GenbankMetadataOrganism {
            get {
                return ResourceManager.GetString("GenbankMetadataOrganism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the selected metadata..
        /// </summary>
        internal static string GenbankMetadataParseError {
            get {
                return ResourceManager.GetString("GenbankMetadataParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string GenbankMetadataPrimary {
            get {
                return ResourceManager.GetString("GenbankMetadataPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PubMed.
        /// </summary>
        internal static string GenbankMetadataPubMed {
            get {
                return ResourceManager.GetString("GenbankMetadataPubMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string GenbankMetadataReference {
            get {
                return ResourceManager.GetString("GenbankMetadataReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string GenbankMetadataRemarks {
            get {
                return ResourceManager.GetString("GenbankMetadataRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        internal static string GenbankMetadataSegment {
            get {
                return ResourceManager.GetString("GenbankMetadataSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq Length.
        /// </summary>
        internal static string GenbankMetadataSeqLength {
            get {
                return ResourceManager.GetString("GenbankMetadataSeqLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq Type.
        /// </summary>
        internal static string GenbankMetadataSeqType {
            get {
                return ResourceManager.GetString("GenbankMetadataSeqType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string GenbankMetadataSource {
            get {
                return ResourceManager.GetString("GenbankMetadataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strand Topology.
        /// </summary>
        internal static string GenbankMetadataStrandTopology {
            get {
                return ResourceManager.GetString("GenbankMetadataStrandTopology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strand Type.
        /// </summary>
        internal static string GenbankMetadataStrandType {
            get {
                return ResourceManager.GetString("GenbankMetadataStrandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string GenbankMetadataTitle {
            get {
                return ResourceManager.GetString("GenbankMetadataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string GenbankMetadataVersion {
            get {
                return ResourceManager.GetString("GenbankMetadataVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string GffColumnEnd {
            get {
                return ResourceManager.GetString("GffColumnEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        internal static string GffColumnFrame {
            get {
                return ResourceManager.GetString("GffColumnFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string GffColumnGroup {
            get {
                return ResourceManager.GetString("GffColumnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string GffColumnName {
            get {
                return ResourceManager.GetString("GffColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string GffColumnScore {
            get {
                return ResourceManager.GetString("GffColumnScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string GffColumnSource {
            get {
                return ResourceManager.GetString("GffColumnSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string GffColumnStart {
            get {
                return ResourceManager.GetString("GffColumnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strand.
        /// </summary>
        internal static string GffColumnStrand {
            get {
                return ResourceManager.GetString("GffColumnStrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string GffColumnType {
            get {
                return ResourceManager.GetString("GffColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} field: {1}..
        /// </summary>
        internal static string GffInvalidField {
            get {
                return ResourceManager.GetString("GffInvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Id.
        /// </summary>
        internal static string GROUP_ID {
            get {
                return ResourceManager.GetString("GROUP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string IDENTITY {
            get {
                return ResourceManager.GetString("IDENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map files which are in {0} to excel.
        /// </summary>
        internal static string IMPORT_DESC {
            get {
                return ResourceManager.GetString("IMPORT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import From {0} files.
        /// </summary>
        internal static string IMPORT_LABEL {
            get {
                return ResourceManager.GetString("IMPORT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range address provided is not valid..
        /// </summary>
        internal static string InputSelection_InvalidRange {
            get {
                return ResourceManager.GetString("InputSelection_InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Region.
        /// </summary>
        internal static string InputSelection_SequenceLabel_BED1 {
            get {
                return ResourceManager.GetString("InputSelection_SequenceLabel_BED1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Region.
        /// </summary>
        internal static string InputSelection_SequenceLabel_BED2 {
            get {
                return ResourceManager.GetString("InputSelection_SequenceLabel_BED2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Sequence.
        /// </summary>
        internal static string InputSelection_SequenceLabel_Blast {
            get {
                return ResourceManager.GetString("InputSelection_SequenceLabel_Blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range A.
        /// </summary>
        internal static string InputSelection_SequenceLabel_Venn1 {
            get {
                return ResourceManager.GetString("InputSelection_SequenceLabel_Venn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range B.
        /// </summary>
        internal static string InputSelection_SequenceLabel_Venn2 {
            get {
                return ResourceManager.GetString("InputSelection_SequenceLabel_Venn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range C.
        /// </summary>
        internal static string InputSelection_SequenceLabel_Venn3 {
            get {
                return ResourceManager.GetString("InputSelection_SequenceLabel_Venn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersect requires atleast 2 query regions.This workbook has less than 2 query regions. Please import another query region and then intersect them..
        /// </summary>
        internal static string INTERSECT_ATLEAST_2_SHEETS {
            get {
                return ResourceManager.GetString("INTERSECT_ATLEAST_2_SHEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersect_Sheet.
        /// </summary>
        internal static string INTERSECT_SHEET {
            get {
                return ResourceManager.GetString("INTERSECT_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid params.
        /// </summary>
        internal static string INVALID_PARAMS {
            get {
                return ResourceManager.GetString("INVALID_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence in {0}.
        /// </summary>
        internal static string INVALID_SEQUENCE {
            get {
                return ResourceManager.GetString("INVALID_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string INVALID_TEXT {
            get {
                return ResourceManager.GetString("INVALID_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string LENGTH {
            get {
                return ResourceManager.GetString("LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayChart macro not found. Please import the macro..
        /// </summary>
        internal static string MACRO_MISSING {
            get {
                return ResourceManager.GetString("MACRO_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max no. of columns : {0}.
        /// </summary>
        internal static string MAXCOLUMNS {
            get {
                return ResourceManager.GetString("MAXCOLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows an about dialog box..
        /// </summary>
        internal static string MENU_ABOUT_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_ABOUT_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Bio.
        /// </summary>
        internal static string MENU_ABOUT_TIP {
            get {
                return ResourceManager.GetString("MENU_ABOUT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an aligner from this drop down and provide input sequences and alignment parameters to perform an alignment..
        /// </summary>
        internal static string MENU_ALIGNERS_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_ALIGNERS_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align two or more sequences.
        /// </summary>
        internal static string MENU_ALIGNERS_TIP {
            get {
                return ResourceManager.GetString("MENU_ALIGNERS_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings up a window where you can select input sequences and assembly parameters and do an assembly..
        /// </summary>
        internal static string MENU_ASSEMBLERS_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_ASSEMBLERS_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemble two or more sequences.
        /// </summary>
        internal static string MENU_ASSEMBLERS_TIP {
            get {
                return ResourceManager.GetString("MENU_ASSEMBLERS_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an operation from this drop down..
        /// </summary>
        internal static string MENU_BED_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_BED_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulate BED files.
        /// </summary>
        internal static string MENU_BED_TIP {
            get {
                return ResourceManager.GetString("MENU_BED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a BLAST search provider from this drop down and follow further instructions to do a BLAST search..
        /// </summary>
        internal static string MENU_BLAST_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_BLAST_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLAST search.
        /// </summary>
        internal static string MENU_BLAST_TIP {
            get {
                return ResourceManager.GetString("MENU_BLAST_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel any running alignment process..
        /// </summary>
        internal static string MENU_CANCELALIGN_TIP {
            get {
                return ResourceManager.GetString("MENU_CANCELALIGN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel any running BLAST search operation..
        /// </summary>
        internal static string MENU_CANCELBLAST_TIP {
            get {
                return ResourceManager.GetString("MENU_CANCELBLAST_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display different types of charts and graphs depending on the sequence data..
        /// </summary>
        internal static string MENU_CHART_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_CHART_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts and Graphs..
        /// </summary>
        internal static string MENU_CHART_TIP {
            get {
                return ResourceManager.GetString("MENU_CHART_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure what color should be displayed for each cell depending on the DNA, RNA or Protein symbol in that cell..
        /// </summary>
        internal static string MENU_CONF_COLOR_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_CONF_COLOR_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure maximum number of cells to be added to a row when importing files..
        /// </summary>
        internal static string MENU_CONF_COLWRAP_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_CONF_COLWRAP_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different configuration options for customizing BioExcel..
        /// </summary>
        internal static string MENU_CONF_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_CONF_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string MENU_CONF_TIP {
            get {
                return ResourceManager.GetString("MENU_CONF_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the data in the current sheet to a file..
        /// </summary>
        internal static string MENU_EXPORT_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_EXPORT_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        internal static string MENU_EXPORT_TIP {
            get {
                return ResourceManager.GetString("MENU_EXPORT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file format from this drop down and choose a file to import..
        /// </summary>
        internal static string MENU_IMPORT_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_IMPORT_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data.
        /// </summary>
        internal static string MENU_IMPORT_TIP {
            get {
                return ResourceManager.GetString("MENU_IMPORT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersect the intervals of two queries.
        /// </summary>
        internal static string MENU_INTERSECT_DESC {
            get {
                return ResourceManager.GetString("MENU_INTERSECT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge the overlapping intervals of a query.
        /// </summary>
        internal static string MENU_MERGE_DESC {
            get {
                return ResourceManager.GetString("MENU_MERGE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract the intervals of two queries.
        /// </summary>
        internal static string MENU_SUBTRACT_DESC {
            get {
                return ResourceManager.GetString("MENU_SUBTRACT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires NodeXL version 1.0.1.108 or later installed on your machine..
        /// </summary>
        internal static string MENU_VENN_NodeXLmissing {
            get {
                return ResourceManager.GetString("MENU_VENN_NodeXLmissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a Venn diagram using two/three sets of BED data..
        /// </summary>
        internal static string MENU_VENN_SUPERTIP {
            get {
                return ResourceManager.GetString("MENU_VENN_SUPERTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Venn diagrams.
        /// </summary>
        internal static string MENU_VENN_TIP {
            get {
                return ResourceManager.GetString("MENU_VENN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires atleast 1 query region.This workbook has less than 1 query region. Please import another query region and then merge them..
        /// </summary>
        internal static string MERGE_ATLEAST_1_SHEETS {
            get {
                return ResourceManager.GetString("MERGE_ATLEAST_1_SHEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged_Sheet.
        /// </summary>
        internal static string MERGED_SHEET {
            get {
                return ResourceManager.GetString("MERGED_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recognize metadata format. Metadata will not be displayed..
        /// </summary>
        internal static string MetadataFormatError {
            get {
                return ResourceManager.GetString("MetadataFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midline.
        /// </summary>
        internal static string MIDLINE {
            get {
                return ResourceManager.GetString("MIDLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minumum Overlap value should be a number..
        /// </summary>
        internal static string MIN_OVERLAP_ERROR {
            get {
                return ResourceManager.GetString("MIN_OVERLAP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 3 columns are required in a BED sheet. {0} does not have 3 columns. Please add atleast 3 columns and try again..
        /// </summary>
        internal static string MINIMUM_3_COLUMNS {
            get {
                return ResourceManager.GetString("MINIMUM_3_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatches.
        /// </summary>
        internal static string MISMATCHES {
            get {
                return ResourceManager.GetString("MISMATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence data is missing in all selected sheets..
        /// </summary>
        internal static string MissingSeqDataInSelectedSheets {
            get {
                return ResourceManager.GetString("MissingSeqDataInSelectedSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation returned no result.
        /// </summary>
        internal static string NO_RESULT {
            get {
                return ResourceManager.GetString("NO_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find user guide document..
        /// </summary>
        internal static string NoUserGuidePresent {
            get {
                return ResourceManager.GetString("NoUserGuidePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nr.25.
        /// </summary>
        internal static string NR_25 {
            get {
                return ResourceManager.GetString("NR_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string NUMBER {
            get {
                return ResourceManager.GetString("NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Ranges.
        /// </summary>
        internal static string NUMBER_OF_RANGES {
            get {
                return ResourceManager.GetString("NUMBER_OF_RANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse {0} : {1}.
        /// </summary>
        internal static string PARSE_ERROR {
            get {
                return ResourceManager.GetString("PARSE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein Sequences are not supported for this operation..
        /// </summary>
        internal static string PROTEIN_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("PROTEIN_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.End.
        /// </summary>
        internal static string QEND {
            get {
                return ResourceManager.GetString("QEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.Start.
        /// </summary>
        internal static string QSTART {
            get {
                return ResourceManager.GetString("QSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryId.
        /// </summary>
        internal static string QUERY_ID {
            get {
                return ResourceManager.GetString("QUERY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string SCORE {
            get {
                return ResourceManager.GetString("SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align two or more sequences using {0} aligner..
        /// </summary>
        internal static string SCREEN_TIP_ALIGNERS {
            get {
                return ResourceManager.GetString("SCREEN_TIP_ALIGNERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a BLAST search on {0} database..
        /// </summary>
        internal static string SCREEN_TIP_BLAST_SEARCH {
            get {
                return ResourceManager.GetString("SCREEN_TIP_BLAST_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export this sheet to a {0} file..
        /// </summary>
        internal static string SCREEN_TIP_EXPORT_MENU {
            get {
                return ResourceManager.GetString("SCREEN_TIP_EXPORT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports one or more {0} files..
        /// </summary>
        internal static string SCREEN_TIP_IMPORT_MENU {
            get {
                return ResourceManager.GetString("SCREEN_TIP_IMPORT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersect overlapping intervals of two sets of genomic interval data..
        /// </summary>
        internal static string SCREEN_TIP_INTERSECT {
            get {
                return ResourceManager.GetString("SCREEN_TIP_INTERSECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge overlapping intervals of one or more set(s) of genomic interval data..
        /// </summary>
        internal static string SCREEN_TIP_MERGE {
            get {
                return ResourceManager.GetString("SCREEN_TIP_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align two sequences using {0} aligner..
        /// </summary>
        internal static string SCREEN_TIP_PAIRWISEALIGNERS {
            get {
                return ResourceManager.GetString("SCREEN_TIP_PAIRWISEALIGNERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract overlapping intervals of two or more sets of genomic interval data..
        /// </summary>
        internal static string SCREEN_TIP_SUBTRACT {
            get {
                return ResourceManager.GetString("SCREEN_TIP_SUBTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string SEARCHING {
            get {
                return ResourceManager.GetString("SEARCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast {0} or more sheets..
        /// </summary>
        internal static string SELECT_SHEET_MESSAGE {
            get {
                return ResourceManager.GetString("SELECT_SHEET_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A column cannot be assigned to more than one header..
        /// </summary>
        internal static string SelectionModel_BED_ColumnMappedMoreThanOnce {
            get {
                return ResourceManager.GetString("SelectionModel_BED_ColumnMappedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse one or more items. Please check the data and the range address provided..
        /// </summary>
        internal static string SelectionModel_ParsingFailed {
            get {
                return ResourceManager.GetString("SelectionModel_ParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.End.
        /// </summary>
        internal static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement.
        /// </summary>
        internal static string SEQUENCE_COMPLEMENT {
            get {
                return ResourceManager.GetString("SEQUENCE_COMPLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Data.
        /// </summary>
        internal static string SEQUENCE_DATA {
            get {
                return ResourceManager.GetString("SEQUENCE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence ID.
        /// </summary>
        internal static string Sequence_ID {
            get {
                return ResourceManager.GetString("Sequence_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Information.
        /// </summary>
        internal static string SEQUENCE_INFO {
            get {
                return ResourceManager.GetString("SEQUENCE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Scores.
        /// </summary>
        internal static string Sequence_QualityScores {
            get {
                return ResourceManager.GetString("Sequence_QualityScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string SEQUENCE_REVERSE {
            get {
                return ResourceManager.GetString("SEQUENCE_REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Complement.
        /// </summary>
        internal static string SEQUENCE_REVERSECOMPLEMENT {
            get {
                return ResourceManager.GetString("SEQUENCE_REVERSECOMPLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceData.
        /// </summary>
        internal static string SEQUENCEDATA {
            get {
                return ResourceManager.GetString("SEQUENCEDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA_.
        /// </summary>
        internal static string SEQUENCEDATA_PRESELECTION {
            get {
                return ResourceManager.GetString("SEQUENCEDATA_PRESELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANGEDATA_.
        /// </summary>
        internal static string SEQUENCERANGEDATA_PRESELECTION {
            get {
                return ResourceManager.GetString("SEQUENCERANGEDATA_PRESELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search similar sequences using {0} webservice.
        /// </summary>
        internal static string SERVICE_DESC {
            get {
                return ResourceManager.GetString("SERVICE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0} database.
        /// </summary>
        internal static string SERVICE_LABEL {
            get {
                return ResourceManager.GetString("SERVICE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq_.
        /// </summary>
        internal static string SHEET_NAME {
            get {
                return ResourceManager.GetString("SHEET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.Start.
        /// </summary>
        internal static string SSTART {
            get {
                return ResourceManager.GetString("SSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string STATUS_READY {
            get {
                return ResourceManager.GetString("STATUS_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectId.
        /// </summary>
        internal static string SUBJECT_ID {
            get {
                return ResourceManager.GetString("SUBJECT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract requires atleast 2 query regions.This workbook has less than 2 query regions. Please import another query region and then subtract them..
        /// </summary>
        internal static string SUBTRACT_ATLEAST_2_SHEETS {
            get {
                return ResourceManager.GetString("SUBTRACT_ATLEAST_2_SHEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract_Sheet.
        /// </summary>
        internal static string SUBTRACT_SHEET {
            get {
                return ResourceManager.GetString("SUBTRACT_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.Pattern.
        /// </summary>
        internal static string TPATTERN {
            get {
                return ResourceManager.GetString("TPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmerged_Sequence.
        /// </summary>
        internal static string UNMERGED_SEQUENCE {
            get {
                return ResourceManager.GetString("UNMERGED_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized GenBank Metadata format at {0}..
        /// </summary>
        internal static string UnrecognizedGenBankMetadataFormat {
            get {
                return ResourceManager.GetString("UnrecognizedGenBankMetadataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Gff Metadata format..
        /// </summary>
        internal static string UnrecognizedGffMetadataFormat {
            get {
                return ResourceManager.GetString("UnrecognizedGffMetadataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Docs\.NET Bio_Extension_for_Excel_User_Guide.docx.
        /// </summary>
        internal static string UserGuideRelativePath {
            get {
                return ResourceManager.GetString("UserGuideRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  value.
        /// </summary>
        internal static string VALUE_TEXT {
            get {
                return ResourceManager.GetString("VALUE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VennIcon {
            get {
                object obj = ResourceManager.GetObject("VennIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service: {0}.
        /// </summary>
        internal static string WEBSERVICE_STATUS_BAR {
            get {
                return ResourceManager.GetString("WEBSERVICE_STATUS_BAR", resourceCulture);
            }
        }
    }
}
