//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelWorkbench.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Designer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Designer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelWorkbench.Properties.Resources.Designer", typeof(Resources_Designer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  could not be parsed. The current operation will be aborted..
        /// </summary>
        internal static string ABORT_BED_PARSING {
            get {
                return ResourceManager.GetString("ABORT_BED_PARSING", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align sequences using  {0} algo.
        /// </summary>
        internal static string ALIGN_LABEL {
            get {
                return ResourceManager.GetString("ALIGN_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string ALIGNING {
            get {
                return ResourceManager.GetString("ALIGNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string ALIGNMENT {
            get {
                return ResourceManager.GetString("ALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment requires atleast 2 sequences.This workbook has less than 2 sequence. Please import another sequence and then align..
        /// </summary>
        internal static string ALIGNMENT_ATLEAST_2_SHEETS {
            get {
                return ResourceManager.GetString("ALIGNMENT_ATLEAST_2_SHEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment: {0}.
        /// </summary>
        internal static string ALIGNMENT_STATUS_BAR {
            get {
                return ResourceManager.GetString("ALIGNMENT_STATUS_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockCount.
        /// </summary>
        internal static string BED_BLOCK_COUNT {
            get {
                return ResourceManager.GetString("BED_BLOCK_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockSizes.
        /// </summary>
        internal static string BED_BLOCK_SIZES {
            get {
                return ResourceManager.GetString("BED_BLOCK_SIZES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockStarts.
        /// </summary>
        internal static string BED_BLOCK_STARTS {
            get {
                return ResourceManager.GetString("BED_BLOCK_STARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemRGB.
        /// </summary>
        internal static string BED_ITEM_RGB {
            get {
                return ResourceManager.GetString("BED_ITEM_RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BED_NAME {
            get {
                return ResourceManager.GetString("BED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string BED_SCORE {
            get {
                return ResourceManager.GetString("BED_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strand.
        /// </summary>
        internal static string BED_STRAND {
            get {
                return ResourceManager.GetString("BED_STRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThickEnd.
        /// </summary>
        internal static string BED_THICK_END {
            get {
                return ResourceManager.GetString("BED_THICK_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThickStart.
        /// </summary>
        internal static string BED_THICK_START {
            get {
                return ResourceManager.GetString("BED_THICK_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cancel the Blast request. {0}.
        /// </summary>
        internal static string BLAST_CANCEL_FAILED {
            get {
                return ResourceManager.GetString("BLAST_CANCEL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results were found.
        /// </summary>
        internal static string BLAST_NO_RESULT {
            get {
                return ResourceManager.GetString("BLAST_NO_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLAST_Results.
        /// </summary>
        internal static string BLAST_RESULTS {
            get {
                return ResourceManager.GetString("BLAST_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Biology Foundation.
        /// </summary>
        internal static string CAPTION {
            get {
                return ResourceManager.GetString("CAPTION", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Charts {
            get {
                object obj = ResourceManager.GetObject("Charts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string CHROM_END {
            get {
                return ResourceManager.GetString("CHROM_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromosome.
        /// </summary>
        internal static string CHROM_ID {
            get {
                return ResourceManager.GetString("CHROM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string CHROM_START {
            get {
                return ResourceManager.GetString("CHROM_START", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Clustered_Chart {
            get {
                object obj = ResourceManager.GetObject("Clustered_Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consortiums.
        /// </summary>
        internal static string CONSORTIUMS {
            get {
                return ResourceManager.GetString("CONSORTIUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sequence Item.
        /// </summary>
        internal static string CONTEXTMENU_DELETE {
            get {
                return ResourceManager.GetString("CONTEXTMENU_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Sequence Item.
        /// </summary>
        internal static string CONTEXTMENU_INSERT {
            get {
                return ResourceManager.GetString("CONTEXTMENU_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle color scheme.
        /// </summary>
        internal static string CONTEXTMENU_TOGGLE_COLORS {
            get {
                return ResourceManager.GetString("CONTEXTMENU_TOGGLE_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contig.
        /// </summary>
        internal static string CONTIG {
            get {
                return ResourceManager.GetString("CONTIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an entire sequence to BLAST..
        /// </summary>
        internal static string CONTIG_BLAST_ERROR {
            get {
                return ResourceManager.GetString("CONTIG_BLAST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msrerbio@microsoft.com.
        /// </summary>
        internal static string DEFAULT_EMAIL {
            get {
                return ResourceManager.GetString("DEFAULT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DivisionCode.
        /// </summary>
        internal static string DIVISION_CODE {
            get {
                return ResourceManager.GetString("DIVISION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to em_rel.
        /// </summary>
        internal static string EM_REL {
            get {
                return ResourceManager.GetString("EM_REL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Value.
        /// </summary>
        internal static string EVALUE {
            get {
                return ResourceManager.GetString("EVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save worksheet contents as {0} file .
        /// </summary>
        internal static string EXPORT_DESC {
            get {
                return ResourceManager.GetString("EXPORT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to {0}  files.
        /// </summary>
        internal static string EXPORT_LABEL {
            get {
                return ResourceManager.GetString("EXPORT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.Pattern.
        /// </summary>
        internal static string FPATTERN {
            get {
                return ResourceManager.GetString("FPATTERN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FromExcel {
            get {
                object obj = ResourceManager.GetObject("FromExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FromText {
            get {
                object obj = ResourceManager.GetObject("FromText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FromWeb {
            get {
                object obj = ResourceManager.GetObject("FromWeb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap openings.
        /// </summary>
        internal static string GAP_OPENINGS {
            get {
                return ResourceManager.GetString("GAP_OPENINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaps.
        /// </summary>
        internal static string GAPS {
            get {
                return ResourceManager.GetString("GAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GINumber.
        /// </summary>
        internal static string GINUMBER {
            get {
                return ResourceManager.GetString("GINUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Id.
        /// </summary>
        internal static string GROUP_ID {
            get {
                return ResourceManager.GetString("GROUP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string IDENTITY {
            get {
                return ResourceManager.GetString("IDENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map files which are in {0} to excel.
        /// </summary>
        internal static string IMPORT_DESC {
            get {
                return ResourceManager.GetString("IMPORT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import From {0} files.
        /// </summary>
        internal static string IMPORT_LABEL {
            get {
                return ResourceManager.GetString("IMPORT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersect requires atleast 2 sequence ranges.This workbook has less than 2 sequence ranges. Please import another sequence range and then intersect them..
        /// </summary>
        internal static string INTERSECT_ATLEAST_2_SHEETS {
            get {
                return ResourceManager.GetString("INTERSECT_ATLEAST_2_SHEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersect_Sheet.
        /// </summary>
        internal static string INTERSECT_SHEET {
            get {
                return ResourceManager.GetString("INTERSECT_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid params.
        /// </summary>
        internal static string INVALID_PARAMS {
            get {
                return ResourceManager.GetString("INVALID_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence in {0}.
        /// </summary>
        internal static string INVALID_SEQUENCE {
            get {
                return ResourceManager.GetString("INVALID_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string INVALID_TEXT {
            get {
                return ResourceManager.GetString("INVALID_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string JOURNAL {
            get {
                return ResourceManager.GetString("JOURNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string LENGTH {
            get {
                return ResourceManager.GetString("LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locus.
        /// </summary>
        internal static string LOCUS {
            get {
                return ResourceManager.GetString("LOCUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayChart macro not found. Please import the macro..
        /// </summary>
        internal static string MACRO_MISSING {
            get {
                return ResourceManager.GetString("MACRO_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max no. of columns : {0}.
        /// </summary>
        internal static string MAXCOLUMNS {
            get {
                return ResourceManager.GetString("MAXCOLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medline.
        /// </summary>
        internal static string MEDLINE {
            get {
                return ResourceManager.GetString("MEDLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires atleast 1 sequence ranges.This workbook has less than 1 sequence ranges. Please import another sequence range and then merge them..
        /// </summary>
        internal static string MERGE_ATLEAST_1_SHEETS {
            get {
                return ResourceManager.GetString("MERGE_ATLEAST_1_SHEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged_Sheet.
        /// </summary>
        internal static string MERGED_SHEET {
            get {
                return ResourceManager.GetString("MERGED_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midline.
        /// </summary>
        internal static string MIDLINE {
            get {
                return ResourceManager.GetString("MIDLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minumum Overlap value should be a number..
        /// </summary>
        internal static string MIN_OVERLAP_ERROR {
            get {
                return ResourceManager.GetString("MIN_OVERLAP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatches.
        /// </summary>
        internal static string MISMATCHES {
            get {
                return ResourceManager.GetString("MISMATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence data is missing in all selected sheets..
        /// </summary>
        internal static string MissingSeqDataInSelectedSheets {
            get {
                return ResourceManager.GetString("MissingSeqDataInSelectedSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation returned no result.
        /// </summary>
        internal static string NO_RESULT {
            get {
                return ResourceManager.GetString("NO_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nr.25.
        /// </summary>
        internal static string NR_25 {
            get {
                return ResourceManager.GetString("NR_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string NUMBER {
            get {
                return ResourceManager.GetString("NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse {0} : {1}.
        /// </summary>
        internal static string PARSE_ERROR {
            get {
                return ResourceManager.GetString("PARSE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PubMed.
        /// </summary>
        internal static string PUBMED {
            get {
                return ResourceManager.GetString("PUBMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.End.
        /// </summary>
        internal static string QEND {
            get {
                return ResourceManager.GetString("QEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.Start.
        /// </summary>
        internal static string QSTART {
            get {
                return ResourceManager.GetString("QSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryId.
        /// </summary>
        internal static string QUERY_ID {
            get {
                return ResourceManager.GetString("QUERY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string REMARKS {
            get {
                return ResourceManager.GetString("REMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string SCORE {
            get {
                return ResourceManager.GetString("SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string SEARCHING {
            get {
                return ResourceManager.GetString("SEARCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast {0} or more sheets..
        /// </summary>
        internal static string SELECT_SHEET_MESSAGE {
            get {
                return ResourceManager.GetString("SELECT_SHEET_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.End.
        /// </summary>
        internal static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Data.
        /// </summary>
        internal static string SEQUENCE_DATA {
            get {
                return ResourceManager.GetString("SEQUENCE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Information.
        /// </summary>
        internal static string SEQUENCE_INFO {
            get {
                return ResourceManager.GetString("SEQUENCE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceData.
        /// </summary>
        internal static string SEQUENCEDATA {
            get {
                return ResourceManager.GetString("SEQUENCEDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DATA.
        /// </summary>
        internal static string SEQUENCEDATA_PRESELECTION {
            get {
                return ResourceManager.GetString("SEQUENCEDATA_PRESELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _METADATA.
        /// </summary>
        internal static string SEQUENCEMETADATA {
            get {
                return ResourceManager.GetString("SEQUENCEMETADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _RANGEDATA.
        /// </summary>
        internal static string SEQUENCERANGEDATA_PRESELECTION {
            get {
                return ResourceManager.GetString("SEQUENCERANGEDATA_PRESELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search similar sequences using {0} webservice.
        /// </summary>
        internal static string SERVICE_DESC {
            get {
                return ResourceManager.GetString("SERVICE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0} database.
        /// </summary>
        internal static string SERVICE_LABEL {
            get {
                return ResourceManager.GetString("SERVICE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq_.
        /// </summary>
        internal static string SHEET_NAME {
            get {
                return ResourceManager.GetString("SHEET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.Start.
        /// </summary>
        internal static string SSTART {
            get {
                return ResourceManager.GetString("SSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectId.
        /// </summary>
        internal static string SUBJECT_ID {
            get {
                return ResourceManager.GetString("SUBJECT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract requires atleast 2 sequence ranges.This workbook has less than 2 sequence ranges. Please import another sequence range and then subtract them..
        /// </summary>
        internal static string SUBTRACT_ATLEAST_2_SHEETS {
            get {
                return ResourceManager.GetString("SUBTRACT_ATLEAST_2_SHEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract_Sheet.
        /// </summary>
        internal static string SUBTRACT_SHEET {
            get {
                return ResourceManager.GetString("SUBTRACT_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.Pattern.
        /// </summary>
        internal static string TPATTERN {
            get {
                return ResourceManager.GetString("TPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmerged_Sequence.
        /// </summary>
        internal static string UNMERGED_SEQUENCE {
            get {
                return ResourceManager.GetString("UNMERGED_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  value.
        /// </summary>
        internal static string VALUE_TEXT {
            get {
                return ResourceManager.GetString("VALUE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service: {0}.
        /// </summary>
        internal static string WEBSERVICE_STATUS_BAR {
            get {
                return ResourceManager.GetString("WEBSERVICE_STATUS_BAR", resourceCulture);
            }
        }
    }
}
