//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SequenceAssembler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SequenceAssembler.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligning Sequences....
        /// </summary>
        internal static string AligningSequences {
            get {
                return ResourceManager.GetString("AligningSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignments.
        /// </summary>
        internal static string Alignments {
            get {
                return ResourceManager.GetString("Alignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignments Tree View.
        /// </summary>
        internal static string AlignmentsTreeView {
            get {
                return ResourceManager.GetString("AlignmentsTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files type.
        /// </summary>
        internal static string ALL_FILE_FORMAT {
            get {
                return ResourceManager.GetString("ALL_FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files|*.*.
        /// </summary>
        internal static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembling Sequences....
        /// </summary>
        internal static string AssemblingSequences {
            get {
                return ResourceManager.GetString("AssemblingSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect.
        /// </summary>
        internal static string AUTO_DETECT_TEXT {
            get {
                return ResourceManager.GetString("AUTO_DETECT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string AutoString {
            get {
                return ResourceManager.GetString("AutoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://blast2.cloudapp.net/BlastService.svc.
        /// </summary>
        internal static string AZURE_URI {
            get {
                return ResourceManager.GetString("AZURE_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad input in file.
        /// </summary>
        internal static string BAD_FILE_ERROR {
            get {
                return ResourceManager.GetString("BAD_FILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits.
        /// </summary>
        internal static string BITS_TEXT {
            get {
                return ResourceManager.GetString("BITS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cancel the Blast request. {0}.
        /// </summary>
        internal static string BLAST_CANCEL_FAILED {
            get {
                return ResourceManager.GetString("BLAST_CANCEL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast output recieved cannot be rendered on SilverMap.
        /// </summary>
        internal static string BLAST_ERROR_TEXT {
            get {
                return ResourceManager.GetString("BLAST_ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Bio Sequence Assembler.
        /// </summary>
        internal static string CAPTION {
            get {
                return ResourceManager.GetString("CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contig.
        /// </summary>
        internal static string CONTIG_TEXT {
            get {
                return ResourceManager.GetString("CONTIG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contigs.
        /// </summary>
        internal static string Contigs {
            get {
                return ResourceManager.GetString("Contigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contigs Tree View.
        /// </summary>
        internal static string ContigsTreeView {
            get {
                return ResourceManager.GetString("ContigsTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to em_rel.
        /// </summary>
        internal static string DATABASE_EM_REL {
            get {
                return ResourceManager.GetString("DATABASE_EM_REL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nr.
        /// </summary>
        internal static string DATABASE_NR {
            get {
                return ResourceManager.GetString("DATABASE_NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nr.25.
        /// </summary>
        internal static string DATABASE_NR_25 {
            get {
                return ResourceManager.GetString("DATABASE_NR_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nt.
        /// </summary>
        internal static string DATABASE_NT {
            get {
                return ResourceManager.GetString("DATABASE_NT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCBI QBLAST.
        /// </summary>
        internal static string DefaultWebService {
            get {
                return ResourceManager.GetString("DefaultWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Few files in the selected files have been already imported. Please import new files..
        /// </summary>
        internal static string DUPLICATE_FILE {
            get {
                return ResourceManager.GetString("DUPLICATE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EDIT_TEXT {
            get {
                return ResourceManager.GetString("EDIT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Offset.
        /// </summary>
        internal static string EndOffset {
            get {
                return ResourceManager.GetString("EndOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the application?.
        /// </summary>
        internal static string EXIT_APPLICATION {
            get {
                return ResourceManager.GetString("EXIT_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.ncbi.nlm.nih.gov/books/bv.fcgi?rid=handbook.glossary.1237#app36.
        /// </summary>
        internal static string FAQ_LINK {
            get {
                return ResourceManager.GetString("FAQ_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FILE_TEXT {
            get {
                return ResourceManager.GetString("FILE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error formatting the file. Please try to save in another format..
        /// </summary>
        internal static string FORMATTING_ERROR {
            get {
                return ResourceManager.GetString("FORMATTING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Letters.
        /// </summary>
        internal static string HEADER_LETTER {
            get {
                return ResourceManager.GetString("HEADER_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File type.
        /// </summary>
        internal static string INVALID_FILE_TYPE {
            get {
                return ResourceManager.GetString("INVALID_FILE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen request parameters are not valid for the selected sequence.
        /// </summary>
        internal static string INVALID_SERVICE_PARAM_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_SERVICE_PARAM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid .
        /// </summary>
        internal static string INVALID_TEXT {
            get {
                return ResourceManager.GetString("INVALID_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Parser.
        /// </summary>
        internal static string MANUAL_CHOICE {
            get {
                return ResourceManager.GetString("MANUAL_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://bio.codeplex.com.
        /// </summary>
        internal static string MBFWebsiteAddress {
            get {
                return ResourceManager.GetString("MBFWebsiteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An alignment was not possible with the given input..
        /// </summary>
        internal static string NoAlignmentPossible {
            get {
                return ResourceManager.GetString("NoAlignmentPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Alignments:.
        /// </summary>
        internal static string NoOfAlignments {
            get {
                return ResourceManager.GetString("NoOfAlignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Contigs:.
        /// </summary>
        internal static string NoOfContigs {
            get {
                return ResourceManager.GetString("NoOfContigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected sequences found..
        /// </summary>
        internal static string NoSequencesSelected {
            get {
                return ResourceManager.GetString("NoSequencesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find user guide document..
        /// </summary>
        internal static string NoUserGuidePresent {
            get {
                return ResourceManager.GetString("NoUserGuidePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the file type association run this application in administrator mode..
        /// </summary>
        internal static string OpenApplicationInAdminMode {
            get {
                return ResourceManager.GetString("OpenApplicationInAdminMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaDeNA.
        /// </summary>
        internal static string PaDeNAString {
            get {
                return ResourceManager.GetString("PaDeNAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} {1}.
        /// </summary>
        internal static string PAIRWISE_BITS {
            get {
                return ResourceManager.GetString("PAIRWISE_BITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAMSAM (MUSCLE).
        /// </summary>
        internal static string PAMSAM {
            get {
                return ResourceManager.GetString("PAMSAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser not found for {0}.
        /// </summary>
        internal static string ParserNotFound {
            get {
                return ResourceManager.GetString("ParserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current operation will result in re-building the consensus/alignment view. All your previous output will be lost. Ensure that you have saved previous output before you proceed. Do you want to continue?.
        /// </summary>
        internal static string REASSEMBLY_WARNING {
            get {
                return ResourceManager.GetString("REASSEMBLY_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        internal static string SAVE_TEXT {
            get {
                return ResourceManager.GetString("SAVE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sequence{0} {1}].
        /// </summary>
        internal static string SEQUENCE_TEXT_CV {
            get {
                return ResourceManager.GetString("SEQUENCE_TEXT_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string SEQUENCE_TEXT_SV {
            get {
                return ResourceManager.GetString("SEQUENCE_TEXT_SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size is too low. Please use 2 or above as font size..
        /// </summary>
        internal static string SequencesPanel_FontSizeLow {
            get {
                return ResourceManager.GetString("SequencesPanel_FontSizeLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add one or more sequences to this workspace to view it..
        /// </summary>
        internal static string SequencesPanel_NothingToDisplay {
            get {
                return ResourceManager.GetString("SequencesPanel_NothingToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while processing BLAST results: {0}.
        /// </summary>
        internal static string SILVERMAP_ERROR_PROCESSING_BLAST_RESULT {
            get {
                return ResourceManager.GetString("SILVERMAP_ERROR_PROCESSING_BLAST_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query sequence.
        /// </summary>
        internal static string SILVERMAP_QUERY_SEQUENCE {
            get {
                return ResourceManager.GetString("SILVERMAP_QUERY_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query ID unknown.
        /// </summary>
        internal static string SILVERMAP_UNKNOWN_QUERY_ID {
            get {
                return ResourceManager.GetString("SILVERMAP_UNKNOWN_QUERY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Offset.
        /// </summary>
        internal static string StartOffset {
            get {
                return ResourceManager.GetString("StartOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.ncbi.nlm.nih.gov/books/bv.fcgi?rid=handbook.chapter.ch4.
        /// </summary>
        internal static string TAXONAMY_LINK {
            get {
                return ResourceManager.GetString("TAXONAMY_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many scaffolds generated, please increase the K-mer length and retry..
        /// </summary>
        internal static string TreeViewLoadTimeOut {
            get {
                return ResourceManager.GetString("TreeViewLoadTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassembled Sequences.
        /// </summary>
        internal static string UNASSEMBLED_TEXT {
            get {
                return ResourceManager.GetString("UNASSEMBLED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload.
        /// </summary>
        internal static string UNLOAD_TEXT {
            get {
                return ResourceManager.GetString("UNLOAD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs\.Net Bio_Sequence_Assembler_User_Guide.docx.
        /// </summary>
        internal static string UserGuideRelativePath {
            get {
                return ResourceManager.GetString("UserGuideRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  value.
        /// </summary>
        internal static string VALUE_TEXT {
            get {
                return ResourceManager.GetString("VALUE_TEXT", resourceCulture);
            }
        }
    }
}
