//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio.DistributeApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bio.DistributeApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: DistributeApp is a command-line utility for distributing tasks
        ///across the nodes of a Windows HPC cluster and aggregating the results.
        ///
        ///Please note that the task to be distributed needs to be specially written
        ///(it must be an IDistributable object; SampleClusterApp.exe is provided for
        ///demonstration purposes) and you must specify how the work is to be distributed
        ///(an IDistributor).
        ///
        ///Usage: DistributeApp.exe /Distributable [IDistributable]
        ///                         /Distributor [IDistribute [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DistributeApp_Help {
            get {
                return ResourceManager.GetString("DistributeApp_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET HPC Cluster Distribute Application v1.0
        ///Copyright (c) 2011, The Outercurve Foundation.
        ///.
        /// </summary>
        internal static string DistributeApp_SplashScreen {
            get {
                return ResourceManager.GetString("DistributeApp_SplashScreen", resourceCulture);
            }
        }
    }
}
