//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bio.Tests.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .bam.
        /// </summary>
        internal static string BAM_FILEEXTENSION {
            get {
                return ResourceManager.GetString("BAM_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM.
        /// </summary>
        internal static string BAM_NAME {
            get {
                return ResourceManager.GetString("BAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes a SequenceAlignmentMap to a particular location, usually a file. 
        ///The output is formatted according to the BAM file format..
        /// </summary>
        internal static string BAMFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("BAMFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A BAMParser reads from a source of binary data that is formatted according to the BAM 
        ///file specification, and converts the data to in-memory SequenceAlignmentMap object..
        /// </summary>
        internal static string BAMPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("BAMPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .fq,.fastq.
        /// </summary>
        internal static string FASTQ_FILEEXTENSION {
            get {
                return ResourceManager.GetString("FASTQ_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes an QualitativeSequence to a particular location, usually a file. The output is formatted according to the FASTQ file format..
        /// </summary>
        internal static string FASTQFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FASTQFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastQ.
        /// </summary>
        internal static string FastQName {
            get {
                return ResourceManager.GetString("FastQName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FastQParser reads from a source of text that is formatted according to the FASTQ file specification, and converts the data to in-memory QualitativeSequence objects..
        /// </summary>
        internal static string FASTQPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FASTQPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .gb,.gbk,.genbank.
        /// </summary>
        internal static string GENBANK_FILEEXTENSION {
            get {
                return ResourceManager.GetString("GENBANK_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenBank.
        /// </summary>
        internal static string GENBANK_NAME {
            get {
                return ResourceManager.GetString("GENBANK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes an ISequence to a particular location, usually a file. The output is formatted
        ///according to the GenBank file format. A method is also provided for quickly accessing
        ///the content in string form for applications that do not need to first write to file..
        /// </summary>
        internal static string GENBANKFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GENBANKFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GenBankParser reads from a source of text that is formatted according to the GenBank flat
        ///file specification, and converts the data to in-memory ISequence objects.  For advanced
        ///users, the ability to select an encoding for the internal memory representation is
        ///provided. There is also a default encoding for each alphabet that may be encountered..
        /// </summary>
        internal static string GENBANKPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GENBANKPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .gff.
        /// </summary>
        internal static string GFF_FILEEXTENSION {
            get {
                return ResourceManager.GetString("GFF_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFF.
        /// </summary>
        internal static string GFF_NAME {
            get {
                return ResourceManager.GetString("GFF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes an ISequence to a particular location, usually a file. The output is formatted
        ///according to the GFF file format. A method is also provided for quickly accessing
        ///the content in string form for applications that do not need to first write to file..
        /// </summary>
        internal static string GFFFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GFFFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GffParser reads from a source of text that is formatted according to the GFF flat
        ///file specification, and converts the data to in-memory ISequence objects.  For advanced
        ///users, the ability to select an encoding for the internal memory representation is
        ///provided. There is also a default encoding for each alphabet that may be encountered..
        /// </summary>
        internal static string GFFPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GFFPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recognize one or more symbol in the sequence: {0}.
        /// </summary>
        internal static string InvalidSymbolInString {
            get {
                return ResourceManager.GetString("InvalidSymbolInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sam.
        /// </summary>
        internal static string SAM_FILEEXTENSION {
            get {
                return ResourceManager.GetString("SAM_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM.
        /// </summary>
        internal static string SAM_NAME {
            get {
                return ResourceManager.GetString("SAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes a SequenceAlignmentMap to a particular location, usually a file. The output is formatted
        ///according to the SAM file format..
        /// </summary>
        internal static string SAMFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("SAMFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SAMParser reads from a source of text that is formatted according to the SAM 
        ///file specification, and converts the data to in-memory SequenceAlignmentMap objects..
        /// </summary>
        internal static string SAMPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("SAMPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implements a simple greedy assembly algorithm for DNA..
        /// </summary>
        internal static string SIMPLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("SIMPLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple-Sequence.
        /// </summary>
        internal static string SIMPLE_NAME {
            get {
                return ResourceManager.GetString("SIMPLE_NAME", resourceCulture);
            }
        }
    }
}
