//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScaffoldUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScaffoldUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad input in file [{0}].
        /// </summary>
        internal static string INVALID_INPUT_FILE {
            get {
                return ResourceManager.GetString("INVALID_INPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaffold Generation Utility v2.0
        ///Copyright (c) 2011-2014, The Outercurve Foundation.
        ///
        ///.
        /// </summary>
        internal static string ScaffoldSplashScreen {
            get {
                return ResourceManager.GetString("ScaffoldSplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:	   ScaffoldUtil.exe [options] &lt;input contig sequence file&gt; &lt;input read sequence file&gt;
        ///
        ///ScaffoldGeneration: Generates scaffold sequences.
        ///Optional Parameters:
        ///-k:&lt;int&gt;           Length of k-mer.
        ///
        ///-d:&lt;int&gt;           Threshold for removing 
        ///                   dangling ends in graph.
        ///
        ///-r:&lt;int&gt;    	   Length Threshold for 
        ///                   removing redundant paths in graph.
        ///
        ///-o:&lt;file&gt;          Output file
        ///
        ///-n:&lt;string&gt;           Clone Library Name 
        ///
        ///-i:&lt;double&gt;         Mean Length of clon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScaffoldUtilHelp {
            get {
                return ResourceManager.GetString("ScaffoldUtilHelp", resourceCulture);
            }
        }
    }
}
