//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio.Algorithms.Alignment.MultipleSequenceAlignment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bio.Algorithms.Alignment.MultipleSequenceAlignment.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimura distance matrix generator.
        /// </summary>
        internal static string KimuraDistanceMatrixGeneratorName {
            get {
                return ResourceManager.GetString("KimuraDistanceMatrixGeneratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kmer counting distance matrix generator.
        /// </summary>
        internal static string KmerDistanceMatrixGeneratorName {
            get {
                return ResourceManager.GetString("KmerDistanceMatrixGeneratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sequence alignment.
        /// </summary>
        internal static string MuscleMultipleAlignmentMethodDescription {
            get {
                return ResourceManager.GetString("MuscleMultipleAlignmentMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAMSAM (MUSCLE).
        /// </summary>
        internal static string MuscleMultipleAlignmentMethodName {
            get {
                return ResourceManager.GetString("MuscleMultipleAlignmentMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needleman-Wunsch profile aligner.
        /// </summary>
        internal static string NeedlemanWunschProfileAlignerName {
            get {
                return ResourceManager.GetString("NeedlemanWunschProfileAlignerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairwise Score distance matrix generator.
        /// </summary>
        internal static string PairwiseScoreDistanceMatrixGeneratorName {
            get {
                return ResourceManager.GetString("PairwiseScoreDistanceMatrixGeneratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive alignment algorithm.
        /// </summary>
        internal static string ProgressiveAlignerName {
            get {
                return ResourceManager.GetString("ProgressiveAlignerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify a read-only collection..
        /// </summary>
        internal static string READ_ONLY_COLLECTION_MESSAGE {
            get {
                return ResourceManager.GetString("READ_ONLY_COLLECTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith-Waterman profile aligner.
        /// </summary>
        internal static string SmithWatermanProfileAlignerName {
            get {
                return ResourceManager.GetString("SmithWatermanProfileAlignerName", resourceCulture);
            }
        }
    }
}
