//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio.Hpc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bio.Hpc.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method must be called inside a using(ParallelOptionsScope) statement..
        /// </summary>
        internal static string called_inside {
            get {
                return ResourceManager.GetString("called_inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot replace an existing ParallelOptionsScope stack. Remove the existing stack first with SuspendParallelOptionsScope().
        /// </summary>
        internal static string Cannot_replace {
            get {
                return ResourceManager.GetString("Cannot_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution, std error file path is {0} characters, which will probably cause HPC to crash..
        /// </summary>
        internal static string Caution {
            get {
                return ResourceManager.GetString("Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Exes.
        /// </summary>
        internal static string Copying_Exes {
            get {
                return ResourceManager.GetString("Copying_Exes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task command line is {0} characters long:
        ///{1}.
        /// </summary>
        internal static string CreateTask {
            get {
                return ResourceManager.GetString("CreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done copying..
        /// </summary>
        internal static string Done_copying {
            get {
                return ResourceManager.GetString("Done_copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Error submitting to cluster .
        /// </summary>
        internal static string Error_Submitting {
            get {
                return ResourceManager.GetString("Error_Submitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking to see if exe&apos;s are already there..
        /// </summary>
        internal static string ExeAlreadyThere {
            get {
                return ResourceManager.GetString("ExeAlreadyThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job already exists. Waiting for it to finish. If this is not correct, then delete the log entry file at {0} and try again..
        /// </summary>
        internal static string Job_already_exists {
            get {
                return ResourceManager.GetString("Job_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job template &apos;{0}&apos; does not exist at specified cluster. Existing templates are:.
        /// </summary>
        internal static string Job_template {
            get {
                return ResourceManager.GetString("Job_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file directory {0} does not exist. Will not write results to log file..
        /// </summary>
        internal static string Log_file_directory {
            get {
                return ResourceManager.GetString("Log_file_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not working how I thought it would.
        /// </summary>
        internal static string Not_working {
            get {
                return ResourceManager.GetString("Not_working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numTry=.
        /// </summary>
        internal static string numTry {
            get {
                return ResourceManager.GetString("numTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed job to cluster {0} with path {1}.
        /// </summary>
        internal static string Processed_job {
            get {
                return ResourceManager.GetString("Processed_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StdOutRelativeDirName: .
        /// </summary>
        internal static string StdOutRelativeDirName {
            get {
                return ResourceManager.GetString("StdOutRelativeDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  submitted..
        /// </summary>
        internal static string submitted {
            get {
                return ResourceManager.GetString("submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting job..
        /// </summary>
        internal static string Submitting_job {
            get {
                return ResourceManager.GetString("Submitting_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Using Default job template....
        /// </summary>
        internal static string SubmitViaAPI3 {
            get {
                return ResourceManager.GetString("SubmitViaAPI3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks failed. Requeuing..
        /// </summary>
        internal static string Tasks_failed {
            get {
                return ResourceManager.GetString("Tasks_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Use -cluster help to see usage..
        /// </summary>
        internal static string User_CluserHelp {
            get {
                return ResourceManager.GetString("User_CluserHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using exe directory specified by user: .
        /// </summary>
        internal static string Using_exe {
            get {
                return ResourceManager.GetString("Using_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing log entry to cluster directory.
        /// </summary>
        internal static string Wait_Writing_log {
            get {
                return ResourceManager.GetString("Wait_Writing_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing log file.
        /// </summary>
        internal static string Writing_log_file {
            get {
                return ResourceManager.GetString("Writing_log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xcopy .
        /// </summary>
        internal static string xcopy {
            get {
                return ResourceManager.GetString("xcopy", resourceCulture);
            }
        }
    }
}
